import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowRight,BarChart3,CalendarDays,Check,ChevronLeft,ChevronRight,Clock,Flame,Gamepad2,HeartPulse,Home as HomeIcon,Lock,Menu,Plus,RotateCcw,Sparkles,Target,Trash2,Trophy,X,BookOpen,Droplets,Dumbbell,Medal,Bell,Settings,ScrollText,Zap,ShieldCheck} from 'lucide-react';
import './styles.css';

const STORAGE='reset66-v4';
const LEGACY='reset66-v3';
const iso=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10);
const dateDiff=(a,b)=>Math.floor((new Date(b)-new Date(a))/86400000);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const dayName=['SUN','MON','TUE','WED','THU','FRI','SAT'];

function makeTasks(){return [
 {id:uid(),name:'Workout',target:'45 minutes',time:'18:00',reminder:false},
];}
function defaults(){return [
 {id:'train',name:'TRAIN',detail:'45 minutes',icon:'dumbbell',color:'lime',required:true,tasks:makeTasks()},
 {id:'water',name:'WATER',detail:'2 litres',icon:'droplets',color:'blue',required:true,tasks:[
  {id:uid(),name:'Morning water',target:'500 ml',time:'07:00',reminder:true},
  {id:uid(),name:'Mid-morning water',target:'500 ml',time:'10:00',reminder:true},
  {id:uid(),name:'Afternoon water',target:'500 ml',time:'14:00',reminder:true},
  {id:uid(),name:'Evening water',target:'500 ml',time:'18:00',reminder:true}
 ]},
 {id:'read',name:'READ',detail:'20 minutes',icon:'book',color:'purple',required:false,tasks:[{id:uid(),name:'Read',target:'20 minutes',time:'20:30',reminder:false}]},
 {id:'nutrition',name:'NUTRITION',detail:'No junk food',icon:'heart',color:'amber',required:true,tasks:[{id:uid(),name:'No junk food',target:'Daily',time:'19:00',reminder:false}]}
]}
function migrate(old){
 const base={startedAt:old.startedAt||iso(new Date()),habits:[],completions:old.completions||{},journals:old.journals||{},setupDone:old.setupDone??false,challengeName:old.challengeName||'MY RESET',xp:0,reminderNotices:{},settings:{notifications:false},dayRewards:{}};
 const oldHabits=old.habits||defaults();
 base.habits=oldHabits.map(h=>({...h,tasks:h.tasks?.length?h.tasks:[{id:`legacy-${h.id}`,name:h.name,target:h.detail||'Daily',time:'',reminder:false}]}));
 const taskByHabit={};base.habits.forEach(h=>taskByHabit[h.id]=h.tasks[0].id);
 for(const [date,arr] of Object.entries(base.completions)){base.completions[date]=arr.map(id=>taskByHabit[id]||id)}
 return base;
}
function freshState(){return {startedAt:iso(new Date()),habits:defaults(),completions:{},journals:{},setupDone:false,challengeName:'MY RESET',xp:0,reminderNotices:{},settings:{notifications:false},dayRewards:{}}}
function load(){try{const raw=localStorage.getItem(STORAGE);if(raw)return migrate(JSON.parse(raw));const old=localStorage.getItem(LEGACY);return old?migrate(JSON.parse(old)):freshState()}catch{return freshState()}}
function save(s){localStorage.setItem(STORAGE,JSON.stringify(s))}
function Icon({name,size=19}){const p={size,strokeWidth:2};return name==='dumbbell'?<Dumbbell {...p}/>:name==='droplets'?<Droplets {...p}/>:name==='book'?<BookOpen {...p}/>:name==='heart'?<HeartPulse {...p}/>:<Target {...p}/>}
function allTasks(habits){return habits.flatMap(h=>h.tasks.map(t=>({...t,habitId:h.id,habitName:h.name,icon:h.icon,color:h.color,required:h.required})))}
function taskLabel(t){return `${t.name}${t.target&&t.target!=='Daily'?` · ${t.target}`:''}`}

function App(){
 const [state,setState]=useState(load);const [tab,setTab]=useState('home');const [menu,setMenu]=useState(false);const [showAdd,setShowAdd]=useState(false);const [showReminder,setShowReminder]=useState(false);const [reviewOpen,setReviewOpen]=useState(false);const [celebrate,setCelebrate]=useState(false);const [selectedDate,setSelectedDate]=useState(iso(new Date()));
 const today=iso(new Date());
 const tasks=useMemo(()=>allTasks(state.habits),[state.habits]);
 const day=Math.min(66,Math.max(1,dateDiff(state.startedAt,today)+1));
 const doneIds=state.completions[today]||[];const completed=doneIds.length;const progress=Math.round(day/66*100);
 const required=tasks.filter(t=>t.required);const requiredDone=required.filter(t=>doneIds.includes(t.id)).length;
 const todayPct=tasks.length?Math.round(completed/tasks.length*100):0;
 const streak=useMemo(()=>{let n=0,d=new Date();for(let i=0;i<66;i++){const a=state.completions[iso(d)]||[];if(required.length&&required.every(t=>a.includes(t.id))){n++;d.setDate(d.getDate()-1)}else break}return n},[state.completions,required.length]);
 const xp=state.xp||Object.values(state.completions).reduce((n,a)=>n+a.length*25,0);const level=Math.max(1,Math.floor(xp/500)+1);const levelXp=xp%500;const levelPct=Math.round(levelXp/500*100);
 function mutate(fn){setState(prev=>{const next=fn(JSON.parse(JSON.stringify(prev)));save(next);return next})}
 function toggle(taskId,date=today){mutate(s=>{const a=new Set(s.completions[date]||[]);if(a.has(taskId)){a.delete(taskId);s.xp=Math.max(0,(s.xp||0)-25)}else{a.add(taskId);s.xp=(s.xp||0)+25}s.completions[date]=[...a];return s})}
 function finishDay(){if(requiredDone<required.length){alert(`Complete all required missions first: ${required.length-requiredDone} remaining.`);return}if(state.dayRewards?.[today]){setCelebrate(true);setTimeout(()=>setCelebrate(false),1600);return}setCelebrate(true);mutate(s=>({...s,xp:(s.xp||0)+100,dayRewards:{...(s.dayRewards||{}),[today]:true}}));setTimeout(()=>setCelebrate(false),2200)}
 function restart(){if(confirm('Start a new 66-day reset? Your current history will be cleared.')){const s=freshState();s.setupDone=true;save(s);setState(s);setTab('home')}}
 function addHabit(h){mutate(s=>{s.habits.push({...h,id:uid(),tasks:[]});return s});setShowAdd(false)}
 function removeHabit(id){mutate(s=>({...s,habits:s.habits.filter(h=>h.id!==id)}))}
 function addTask(habitId,t){mutate(s=>{const h=s.habits.find(x=>x.id===habitId);if(h)h.tasks.push({...t,id:uid()});return s})}
 function updateTask(habitId,taskId,patch){mutate(s=>{const h=s.habits.find(x=>x.id===habitId);const t=h?.tasks.find(x=>x.id===taskId);if(t)Object.assign(t,patch);return s})}
 function removeTask(habitId,taskId){mutate(s=>{const h=s.habits.find(x=>x.id===habitId);if(h)h.tasks=h.tasks.filter(t=>t.id!==taskId);return s})}
 function enableNotifications(){if(!('Notification'in window)){alert('This browser does not support notifications.');return}Notification.requestPermission().then(p=>{mutate(s=>({...s,settings:{...s.settings,notifications:p==='granted'}}));if(p!=='granted')alert('Notifications were not enabled. Check your browser/site notification settings.')})}
 useEffect(()=>{const timer=setInterval(()=>{if(!state.settings?.notifications||!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date();const hm=now.toTimeString().slice(0,5);const key=`${iso(now)}-${hm}`;if(state.reminderNotices?.[key])return;const due=tasks.filter(t=>t.reminder&&t.time===hm);if(!due.length)return;due.forEach(t=>new Notification(`RESET 66 · ${t.habitName}`,{body:`${t.name}${t.target&&t.target!=='Daily'?` — ${t.target}`:''}`,tag:t.id}));mutate(s=>{s.reminderNotices[key]=true;return s})},20000);return()=>clearInterval(timer)},[state.settings?.notifications,tasks]);
 if(!state.setupDone)return <Setup onStart={name=>mutate(s=>({...s,challengeName:name||'MY RESET',setupDone:true}))}/>;
 const journal=state.journals[selectedDate]||{mood:4,energy:8,good:'',better:''};
 return <div className="app arcadeShell">
  <aside className="sideRail">
    <button className="sideBrand" onClick={()=>setTab('home')}><div className="sideLogoMark"><Gamepad2/></div><div><b>RESET <span>66</span></b><small>BETTER EVERY DAY</small></div></button>
    <div className="railPlayer"><div className="railAvatar"><Gamepad2/></div><div><b>{state.challengeName}</b><span>LEVEL {level} · MOMENTUM</span></div></div>
    <div className="railNav"><Nav active={tab==='home'} label="HOME" icon={<HomeIcon/>} onClick={()=>setTab('home')}/><Nav active={tab==='habits'} label="MISSIONS" icon={<Target/>} onClick={()=>setTab('habits')}/><Nav active={tab==='progress'} label="JOURNEY" icon={<BarChart3/>} onClick={()=>setTab('progress')}/><Nav active={tab==='journal'} label="PLAYER LOG" icon={<ScrollText/>} onClick={()=>setTab('journal')}/></div>
    <div className="railQuote">“DISCIPLINE<br/>TODAY<br/>FREEDOM<br/>TOMORROW”</div>
    <button className="railSettings" onClick={()=>setMenu(!menu)}><Settings/> SYSTEM</button>
  </aside>
  <div className="gameViewport">
   <header className="topbar"><div className="mobileBrand"><Gamepad2/> RESET<span>66</span></div><div className="topStats"><span><Flame size={15}/>{streak}<em>DAY STREAK</em></span><span><Zap size={15}/>{level}<em>LEVEL</em></span><span><Medal size={15}/>{achievementData(day,streak).filter(a=>a.unlocked).length}<em>BADGES</em></span></div><button className="iconBtn arcadeMini" onClick={()=>setMenu(!menu)}><Menu/></button></header>
   {menu&&<div className="menuPanel"><div className="menuTitle">SYSTEM CONTROL</div><button onClick={enableNotifications}><Bell/> {state.settings?.notifications?'NOTIFICATIONS ON':'ENABLE NOTIFICATIONS'}</button><button onClick={()=>setShowReminder(true)}><Clock/> REMINDER CENTRE</button><button onClick={restart}><RotateCcw/> NEW 66-DAY RUN</button><div className="menuNote">Progress is stored locally on this device. Background push can be added with a cloud notification service.</div></div>}
   <main>
    {tab==='home'&&<Home state={state} day={day} progress={progress} level={level} xp={xp} levelXp={levelXp} levelPct={levelPct} completed={completed} tasks={tasks} streak={streak} todayPct={todayPct} toggle={toggle} finishDay={finishDay} requiredDone={requiredDone} required={required} openReview={()=>setReviewOpen(true)} setTab={setTab}/>} 
    {tab==='habits'&&<Habits state={state} tasks={tasks} toggle={toggle} doneIds={doneIds} onAdd={()=>setShowAdd(true)} onRemove={removeHabit} onAddTask={addTask} onUpdateTask={updateTask} onRemoveTask={removeTask} enableNotifications={enableNotifications}/>} 
    {tab==='progress'&&<Progress state={state} day={day} streak={streak} level={level} xp={xp} editDate={k=>{setSelectedDate(k);setTab('journal')}}/>} 
    {tab==='journal'&&<Journal date={selectedDate} initial={journal} save={(k,j)=>mutate(s=>({...s,journals:{...s.journals,[k]:j}}))}/>} 
   </main>
   <nav className="bottomNav"><Nav active={tab==='home'} label="HOME" icon={<HomeIcon/>} onClick={()=>setTab('home')}/><Nav active={tab==='habits'} label="MISSIONS" icon={<Target/>} onClick={()=>setTab('habits')}/><Nav active={tab==='progress'} label="JOURNEY" icon={<BarChart3/>} onClick={()=>setTab('progress')}/><Nav active={tab==='journal'} label="LOG" icon={<ScrollText/>} onClick={()=>setTab('journal')}/></nav>
   {showAdd&&<AddHabit onClose={()=>setShowAdd(false)} onAdd={addHabit}/>} {showReminder&&<ReminderCentre state={state} tasks={tasks} onClose={()=>setShowReminder(false)} onEnable={enableNotifications}/>} {reviewOpen&&<WeeklyReview state={state} streak={streak} onClose={()=>setReviewOpen(false)}/>} {celebrate&&<Celebration day={day} level={level}/>} 
  </div>
 </div>
}
function Nav({active,label,icon,onClick}){return <button className={active?'nav active arcadeNav':'nav arcadeNav'} onClick={onClick}>{icon}<span>{label}</span></button>}
function Setup({onStart}){const[name,setName]=useState('MY RESET');return <div className="setup gameSetup"><div className="setupGlow"/><div className="setupLogo"><Gamepad2/> RESET<span>66</span></div><div className="eyebrow">PLAYER 01 · THE 66-DAY QUEST</div><h1>LEVEL UP<br/><em>YOUR LIFE.</em></h1><p>66 days. Daily missions. XP, streaks and milestones. Build your system, unlock the next stage and finish the run.</p><label className="fieldLabel">NAME YOUR QUEST</label><input value={name} onChange={e=>setName(e.target.value)}/><button className="primary arcade big" onClick={()=>onStart(name)}>START QUEST <ArrowRight/></button><small>Your progress stays on this device. You can add reminders from the Habit screen.</small></div>}
function Home({state,day,progress,level,xp,levelXp,levelPct,completed,tasks,streak,todayPct,toggle,finishDay,requiredDone,required,openReview,setTab}){
 const today=iso(new Date());
 const badges=achievementData(day,streak);
 const nextCheckpoint=[7,14,21,33,45,56,66].find(n=>n>day)||66;
 const questPct=Math.round(day/66*100);
 return <section className="page gamePage homeGame">
  <div className="dashboardHead"><div><div className="eyebrow">PLAYER 01 · ACTIVE RUN</div><h1>YOUR QUEST <span>CONTINUES.</span></h1><p>Small missions. Visible progress. One finished game.</p></div><div className="headActions"><button className="arcadePill" onClick={()=>setTab('habits')}><Plus/> ADD MISSION</button><button className="arcadePill dark" onClick={()=>setTab('progress')}><Target/> JOURNEY</button></div></div>
  <div className="dashboardGrid">
   <section className="playerCard panel3d"><div className="playerCardTop"><div className="playerAvatar"><Gamepad2/></div><div className="playerCardIdentity"><span>PLAYER</span><b>{state.challengeName}</b><small>LEVEL {level} · MOMENTUM</small><div className="levelTrack"><i style={{width:`${levelPct}%`}}/></div><em>{levelXp} / 500 XP TO LEVEL {level+1}</em></div><div className="bigStats"><div><Flame/><b>{streak}</b><span>DAY STREAK</span></div><div><Trophy/><b>{questPct}%</b><span>QUEST</span></div><div><Medal/><b>{badges.filter(a=>a.unlocked).length}</b><span>BADGES</span></div></div></div></section>
   <section className="promoCard panel3d"><div className="promoArt"/><div className="promoOverlay"><span>THE RESET CODE</span><b>SMALL STEPS<br/>BIG RESULTS</b></div></section>
   <section className="journeyHero panel3d"><div className="journeyArt"><div className="heroMist"/><div className="heroMoon"/><div className="mountain m1"/><div className="mountain m2"/><div className="mountain m3"/><div className="heroTrail"><i style={{width:`${questPct}%`}}/></div><div className="heroPath">{[1,7,14,21,33,45,56,66].map(n=><div key={n} className={'heroNode '+(day>=n?'on ':'')+(day===n?'current':'')} style={{left:`${Math.max(7,Math.min(93,(n/66)*100))}%`,bottom:`${10+(n/66)*62}%`}}><span>{day>=n?<Check/>:<Lock/>}</span><b>{n===66?'NEW YOU':`DAY ${n}`}</b></div>)}</div><div className="heroCaption"><span>SAME YOU · STRONGER VERSION</span><b>DAY {day} / 66</b><small>NEXT UNLOCK · DAY {nextCheckpoint}</small></div><div className="heroBadge"><Trophy/><span>CHECKPOINT</span><b>{day===66?'FINAL BOSS':'IN PROGRESS'}</b></div></div></section>
   <aside className="todayPanel panel3d"><div className="todayHeader"><div><span>TODAY</span><b>{new Date().toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'})}</b></div><div className="dayArrows"><button>‹</button><button>›</button></div></div><div className="scoreRing" style={{'--score':`${todayPct*3.6}deg`}}><div><b>{completed}</b><span>/ {tasks.length}</span><small>TASKS DONE</small></div></div><button className="primary arcade todayCta" onClick={finishDay}>{requiredDone===required.length?'CLAIM DAY REWARD':'KEEP GOING'} <ArrowRight/></button><div className="todayMeta"><span><Zap/> +{completed*25} XP</span><span><Target/> {requiredDone}/{required.length} required</span></div></aside>
   <section className="missionsPanel panel3d"><div className="panelHeading"><div><span>MISSION BOARD</span><h2>TODAY'S MISSIONS</h2></div><b>{completed}/{tasks.length} COMPLETE <ArrowRight/></b></div><div className="missionGrid arcadeMissionGrid">{state.habits.map(h=>{const hs=h.tasks;const done=hs.filter(t=>(state.completions[today]||[]).includes(t.id)).length;return <div className={'missionCard deluxe '+(done===hs.length&&hs.length?'cleared':'')} key={h.id}><div className="missionGlow"/><div className="missionHead"><div className={'habitIcon '+h.color}><Icon name={h.icon}/></div><div><b>{h.name}</b><span>{h.detail}</span></div><strong>{done}/{hs.length}</strong></div><div className="subtaskPreview">{hs.slice(0,5).map(t=>{const ok=(state.completions[today]||[]).includes(t.id);return <button key={t.id} className={ok?'subtask done':'subtask'} onClick={()=>toggle(t.id)}><span className="subCheck">{ok?<Check/>:null}</span><span>{t.name}</span>{t.time&&<small>{t.time}</small>}</button>})}</div><div className="miniProgress"><i style={{width:`${hs.length?done/hs.length*100:0}%`}}/></div><button className="missionOpen" onClick={()=>setTab('habits')}>OPEN <ArrowRight/></button></div>})}</div></section>
   <aside className="rewardPanel panel3d"><div className="rewardTitle"><span>NEXT REWARD</span><Trophy/></div><div className="chest">✦</div><b>{nextCheckpoint===66?'RESET COMPLETE':'HABIT MASTER'}</b><span>{Math.max(0,nextCheckpoint-day)} days until unlock</span><div className="rewardBar"><i style={{width:`${Math.min(100,(day/nextCheckpoint)*100)}%`}}/></div></aside>
  </div>
  <div className="arcadeDock"><button onClick={()=>setTab('progress')}><Target/><b>VIEW JOURNEY</b><small>MAP</small></button><button onClick={()=>setTab('habits')}><Plus/><b>ADD HABIT</b><small>BUILD</small></button><button onClick={()=>setTab('home')} className="dockMain"><Gamepad2/><b>QUICK COMPLETE</b><small>PLAY</small></button><button onClick={openReview}><Medal/><b>WEEKLY REVIEW</b><small>BOSS</small></button><button onClick={()=>setTab('progress')}><Trophy/><b>ACHIEVEMENTS</b><small>BADGES</small></button></div>
  <div className="quote"><Sparkles/><div><b>DISCIPLINE TODAY · FREEDOM TOMORROW</b><span>Every completed mission adds XP and moves your character toward Day 66.</span></div></div>
 </section>}
function Habits({state,tasks,toggle,doneIds,onAdd,onRemove,onAddTask,onUpdateTask,onRemoveTask,enableNotifications}){return <section className="page gamePage"><PageHead title="MISSION BUILDER" kicker="BUILD YOUR DAILY SYSTEM" sub="Break habits into smaller missions and schedule reminders."/><div className="builderBanner"><ShieldCheck/><div><b>MISSION CONTROL</b><span>Each habit can contain unlimited subtasks, times and reminders.</span></div><button className="arcadeSmall" onClick={enableNotifications}><Bell/> {typeof Notification!=='undefined'&&Notification.permission==='granted'?'NOTIFICATIONS ON':'ENABLE'}</button></div><div className="habitList">{state.habits.map(h=><HabitGroup key={h.id} h={h} doneIds={doneIds} toggle={toggle} onRemove={onRemove} onAddTask={onAddTask} onUpdateTask={onUpdateTask} onRemoveTask={onRemoveTask}/>)}</div><button className="secondary arcade addBtn" onClick={onAdd}><Plus/> CREATE NEW HABIT</button></section>}
function HabitGroup({h,doneIds,toggle,onRemove,onAddTask,onUpdateTask,onRemoveTask}){const[open,setOpen]=useState(true);const[adding,setAdding]=useState(false);const[name,setName]=useState('');const[target,setTarget]=useState('');const[time,setTime]=useState('');const[reminder,setReminder]=useState(false);const done=h.tasks.filter(t=>doneIds.includes(t.id)).length;function add(){if(!name.trim())return;onAddTask(h.id,{name:name.trim(),target:target||'Daily',time,reminder});setName('');setTarget('');setTime('');setReminder(false);setAdding(false)}return <div className="habitGroup"><div className="groupHead"><button className="groupMain" onClick={()=>setOpen(!open)}><div className={'habitIcon '+h.color}><Icon name={h.icon}/></div><div><b>{h.name}</b><span>{h.detail} · {done}/{h.tasks.length} complete</span></div></button><div className="groupActions"><button onClick={()=>setAdding(true)}><Plus/></button><button onClick={()=>onRemove(h.id)}><Trash2/></button></div></div>{open&&<div className="subtasks">{h.tasks.map(t=><TaskEditor key={t.id} task={t} checked={doneIds.includes(t.id)} onToggle={()=>toggle(t.id)} onUpdate={p=>onUpdateTask(h.id,t.id,p)} onRemove={()=>onRemoveTask(h.id,t.id)}/>) }{adding&&<div className="newTask"><input autoFocus placeholder="Mission name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Target e.g. 500 ml" value={target} onChange={e=>setTarget(e.target.value)}/><div className="taskInputs"><input type="time" value={time} onChange={e=>setTime(e.target.value)}/><label className="reminderToggle"><input type="checkbox" checked={reminder} onChange={e=>setReminder(e.target.checked)}/><Bell size={15}/> REMIND</label></div><div className="taskButtons"><button className="secondary" onClick={()=>setAdding(false)}>CANCEL</button><button className="primary arcade" onClick={add}>ADD MISSION <Plus/></button></div></div>}</div>}</div>}
function TaskEditor({task,checked,onToggle,onUpdate,onRemove}){return <div className={'taskEditor '+(checked?'done':'')}><button className="taskCheck" onClick={onToggle}>{checked?<Check/>:null}</button><div className="taskCore"><input className="taskName" value={task.name} onChange={e=>onUpdate({name:e.target.value})}/><input className="taskTarget" value={task.target} onChange={e=>onUpdate({target:e.target.value})}/></div><div className="taskSchedule"><label><Clock size={13}/><input type="time" value={task.time||''} onChange={e=>onUpdate({time:e.target.value})}/></label><label className="bellToggle"><input type="checkbox" checked={!!task.reminder} onChange={e=>onUpdate({reminder:e.target.checked})}/><Bell size={14}/></label><button onClick={onRemove}><Trash2/></button></div></div>}
function PageHead({title,kicker,sub}){return <div className="pageHead"><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{sub}</p></div>}
function Progress({state,day,streak,level,xp,editDate}){const tasks=allTasks(state.habits);const total=tasks.length*day;const done=Object.values(state.completions).flat().filter(x=>tasks.some(t=>t.id===x)).length;const consistency=total?Math.round(done/total*100):0;const cells=[];for(let i=0;i<66;i++){const d=new Date(state.startedAt);d.setDate(d.getDate()+i);const k=iso(d),a=state.completions[k]||[],req=tasks.filter(t=>t.required),ok=i<day&&req.length&&req.every(t=>a.includes(t.id)),partial=i<day&&a.length;cells.push(<button onClick={()=>editDate(k)} key={i} className={'dayCell '+(ok?'done ':'')+(partial&&!ok?'partial ':'')+(i===day-1?'current':'')}>{i+1}</button>)}return <section className="page gamePage"><PageHead title="JOURNEY MAP" kicker="YOUR RUN" sub="Every day is another checkpoint toward the final unlock."/><div className="metricGrid"><Metric value={`LV ${level}`} label={`${xp} XP`} icon={<Zap/>}/><Metric value={`${streak}`} label="STREAK" icon={<Flame/>}/><Metric value={`${consistency}%`} label="CONSISTENCY" icon={<Target/>}/></div><div className="card arcadeCard"><div className="cardHead"><b>66-DAY CHECKPOINTS</b><Trophy/></div><div className="checkpointGrid">{[1,7,14,21,33,45,56,66].map(n=><div className={day>=n?'checkpoint unlocked':'checkpoint'} key={n}><div>{day>=n?<Check/>:<Lock/>}</div><b>DAY {n}</b><span>{n===1?'FOUNDATION':n===7?'MOMENTUM':n===14?'DISCIPLINE':n===21?'RESILIENCE':n===33?'HALFWAY':n===45?'CONSISTENCY':n===56?'MASTERY':'NEW YOU'}</span></div>)}</div></div><div className="card"><div className="cardHead"><b>MISSION PERFORMANCE</b><span>{day} days</span></div>{state.habits.map(h=>{const n=h.tasks.reduce((sum,t)=>sum+Object.values(state.completions).filter(a=>a.includes(t.id)).length,0),pct=day&&h.tasks.length?Math.round(n/(day*h.tasks.length)*100):0;return <div className="barRow" key={h.id}><span>{h.name}</span><div><i style={{width:`${Math.min(100,pct)}%`}}/></div><b>{pct}%</b></div>})}</div><div className="card"><div className="cardHead"><b>ACHIEVEMENT ARCADE</b><Medal/></div><div className="achievementGrid">{achievementData(day,streak).map(a=><div className={'achievement '+(a.unlocked?'unlocked':'')} key={a.id}><div className="achievementIcon">{a.unlocked?<Trophy/>:<Lock/>}</div><b>{a.title}</b><span>{a.detail}</span></div>)}</div></div><div className="card"><div className="cardHead"><b>66-DAY CALENDAR</b><CalendarDays/></div><div className="calendar">{cells}</div><div className="legend"><span><i className="lg doneLg"/>Complete</span><span><i className="lg partialLg"/>Partial</span><span><i className="lg"/>Locked</span></div></div></section>}
function achievementData(day,streak){return [{id:'start',title:'FIRST STEP',detail:'Complete Day 1',unlocked:day>=1},{id:'week',title:'7 DAY STREAK',detail:'Hold the line for 7 days',unlocked:streak>=7},{id:'fortnight',title:'14 DAY STREAK',detail:'Two weeks locked in',unlocked:streak>=14},{id:'month',title:'30 DAY STREAK',detail:'Build the machine',unlocked:streak>=30},{id:'half',title:'HALFWAY',detail:'Reach checkpoint 33',unlocked:day>=33},{id:'finish',title:'RESET COMPLETE',detail:'Reach Day 66',unlocked:day>=66}]}
function Metric({value,label,icon}){return <div className="metric"><div>{icon}</div><b>{value}</b><span>{label}</span></div>}
function Journal({date,initial,save}){const[j,setJ]=useState(initial);useEffect(()=>setJ(initial),[date]);return <section className="page gamePage"><PageHead title="PLAYER LOG" kicker="DAILY REFLECTION" sub="Record what happened between checkpoints."/><div className="card"><div className="cardHead"><b>HOW WAS TODAY?</b><span>{date}</span></div><div className="moods">{['😫','😐','🙂','😄','🔥'].map((m,i)=><button className={j.mood===i+1?'selected arcadeSmall':''} onClick={()=>setJ({...j,mood:i+1})} key={m}>{m}</button>)}</div></div><div className="card"><div className="cardHead"><b>ENERGY</b><strong>{j.energy}/10</strong></div><input className="range" type="range" min="1" max="10" value={j.energy} onChange={e=>setJ({...j,energy:+e.target.value})}/></div><label className="textareaLabel">MISSION REPORT · WHAT WENT WELL?</label><textarea value={j.good} onChange={e=>setJ({...j,good:e.target.value})} placeholder="Log the win..."/><label className="textareaLabel">MISSION REPORT · WHAT COULD BE BETTER?</label><textarea value={j.better} onChange={e=>setJ({...j,better:e.target.value})} placeholder="Identify the obstacle..."/><button className="primary arcade finish" onClick={()=>{save(date,j);alert('Player log saved.')}}>SAVE LOG <Check/></button></section>}
function AddHabit({onClose,onAdd}){const[name,setName]=useState(''),[detail,setDetail]=useState(''),[required,setRequired]=useState(false),[icon,setIcon]=useState('target'),[color,setColor]=useState('lime');return <div className="modalBack"><div className="modal"><div className="modalHead"><b>CREATE MISSION GROUP</b><button onClick={onClose}><X/></button></div><label>HABIT / GROUP NAME</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. FITNESS"/><label>MAIN TARGET</label><input value={detail} onChange={e=>setDetail(e.target.value)} placeholder="e.g. 45 minutes daily"/><label>ICON</label><div className="choiceRow">{['target','dumbbell','droplets','book','heart'].map(x=><button className={icon===x?'choice selected':'choice'} onClick={()=>setIcon(x)} key={x}><Icon name={x}/></button>)}</div><label>ACCENT</label><div className="choiceRow">{['lime','blue','purple','amber'].map(x=><button className={'colorChoice '+x+(color===x?' selected':'')} onClick={()=>setColor(x)} key={x}/>)}</div><button className={'toggle '+(required?'on':'')} onClick={()=>setRequired(!required)}><span/>REQUIRED TO CLEAR THE DAY</button><button className="primary arcade" disabled={!name.trim()} onClick={()=>onAdd({name:name.toUpperCase(),detail:detail||'Daily',icon,color,required})}>CREATE GROUP <Plus/></button></div></div>}
function ReminderCentre({state,tasks,onClose,onEnable}){const reminders=tasks.filter(t=>t.reminder);return <div className="modalBack"><div className="modal"><div className="modalHead"><b>REMINDER CENTRE</b><button onClick={onClose}><X/></button></div><div className="reminderHero"><Bell/><div><b>{reminders.length} ACTIVE REMINDERS</b><span>Choose times inside Mission Builder.</span></div></div><button className="primary arcade" onClick={onEnable}><Bell/> ENABLE PUSH NOTIFICATIONS</button><div className="reminderList">{reminders.map(t=><div key={t.id}><span>{t.habitName} · {t.name}</span><b>{t.time||'NO TIME'}</b></div>)}</div><p className="reviewText">The current version can show browser notifications while the app is active. For guaranteed reminders when the app is completely closed, the next infrastructure step is a cloud push service.</p></div></div>}
function Celebration({day,level}){return <div className="celebrate"><div className="celebrateBurst"><Trophy/></div><div className="eyebrow">CHECKPOINT CLEARED · DAY {day}</div><h2>LEVEL UP.</h2><p>+100 XP · Level {level} momentum locked in.</p><div className="celebrateLine"/></div>}
function WeeklyReview({state,streak,onClose}){const req=allTasks(state.habits).filter(t=>t.required);let done=0;for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const a=state.completions[iso(d)]||[];if(req.length&&req.every(t=>a.includes(t.id)))done++}const score=Math.round(done/7*100);return <div className="modalBack"><div className="modal reviewModal"><div className="modalHead"><b>WEEKLY BOSS REVIEW</b><button onClick={onClose}><X/></button></div><div className="reviewHero"><span>WEEKLY SCORE</span><b>{score}%</b><small>{streak} day current streak</small></div><div className="reviewRow"><span>QUEST RULE</span><b>Consistency &gt; perfection</b></div><p className="reviewText">Keep the missions small enough to complete, then protect the streak. The objective is to clear the next checkpoint.</p><button className="primary arcade" onClick={onClose}>CONTINUE QUEST <ArrowRight/></button></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
